### ISSUE TITLE
Typescript 4.9.4 Breaks Decorator

### ISSUE THREAD

**Issue by kubikowski** [garretpremo/rxjs-observed-decorator#11]
## Description:

Using the latest version of Typescript breaks how this decorator interacts with objects & their prototypes.

On initial function call, this decorator does an `Object.defineProperty` on the object prototype, which is passed in as `target`. Then, when a value is set on the object _(this)_, it calls the prototype setter. Which in turn does a second `Object.defineProperty` on the object itself _(this)_. That second `Object.defineProperty` is what allows individual objects to have individual `BehaviorSubjects`, and individual values.

But now, with Typescript 4.9.4, this interaction is broken. Typescript is overwriting the object itself _(this)_ with the object keys that are defined on the class. So, instead of calling the prototype methods, and having getters and setters on the _this_ object, it is running into default defined fields, which are not observed.

### Example with Typescript@4.8.4:

```typescript
// compile time
class MyClass {
    @Observed() myString = "this is a string";
    myString$: Observable<string>;
}

// run time
{
    get myString(), // "this is a string"
    set myString(),
    get "myString$"(), // Observable<"this is a string">
    set "myString$"(),
    __proto__: {
        get myString(), // null
        set myString(),
        get "myString$"(), // Observable<null>
        set "myString$"(),
    }
}
```

### Example with Typescript@4.9.4:

```typescript
// compile time
class MyClass {
    @Observed() myString = "this is a string";
    myString$: Observable<string>;
}

// run time
{
    myString: "this is a string",
    "myString$": undefined,
    __proto__: {
        get myString(), // null
        set myString(),
        get "myString$"(), // Observable<null>
        set "myString$"(),
    }
}
```

## Steps to Reproduce:
Upgrade the dependencies of this project to the following. Then run `build` & `test` scripts.
```
"ts-node": "10.9.1",
"typescript": "4.9.4",
```

**Comment by gpremo-re** [comment]
This issue stumped me for a while, and then I came across [this post](https://stackoverflow.com/questions/68941453/why-have-typescript-property-decorators-stopped-working-after-an-upgrade)

Setting `"useDefineForClassFields": false` in the `tsconfig.json` solves this issue.

For some reason, updating the above dependencies is defaulting this value to `true`, and causing the decorator to break.

The updated configuration:
```
// tsconfig.json
{
  "compilerOptions": {
    ...
    "useDefineForClassFields": false,
    ...
  }
}
```

**Comment by garretpremo** [comment]
This issue stumped me for a while, and then I came across [this post](https://stackoverflow.com/questions/68941453/why-have-typescript-property-decorators-stopped-working-after-an-upgrade)

Setting "useDefineForClassFields": false in the tsconfig.json solves this issue.

For some reason, updating the above dependencies is defaulting this value to true, and causing the decorator to break.

The updated configuration:

// tsconfig.json
{
  "compilerOptions": {
    ...
    "useDefineForClassFields": false,
    ...
  }
}
